# **Tensors**

In [1]:
import torch 

#empty tensor
x = torch.empty(3, 3)
x

tensor([[-5.4034e+11,  4.5661e-41, -5.4034e+11],
        [ 4.5661e-41, -5.6967e-39,  4.5661e-41],
        [-5.6466e-39,  4.5661e-41, -4.5076e-32]])

In [2]:
#random tensor
x = torch.rand(3,3)
x

tensor([[0.8355, 0.9963, 0.8944],
        [0.4939, 0.3926, 0.9050],
        [0.1120, 0.6567, 0.6455]])

In [3]:
#tensor with dtype param
x = torch.ones(2,2, dtype=torch.float32)
x, x.dtype

(tensor([[1., 1.],
         [1., 1.]]),
 torch.float32)

In [4]:
#List to Tensor

x = torch.tensor([1,0,2,3])
x

tensor([1, 0, 2, 3])

# **Basic Operations**

In [5]:
x = torch.rand(2,4)
y = torch.rand(2,4)
x, y

(tensor([[0.9450, 0.1648, 0.3689, 0.8093],
         [0.7535, 0.9527, 0.3047, 0.4240]]),
 tensor([[0.8039, 0.6142, 0.4769, 0.9272],
         [0.4045, 0.9923, 0.0176, 0.6640]]))

In [6]:
# addition / subtraction
z = x + y
z

tensor([[1.7489, 0.7789, 0.8458, 1.7365],
        [1.1580, 1.9449, 0.3223, 1.0880]])

In [7]:
# multiplication
z = torch.mul(x, y)
z

tensor([[0.7597, 0.1012, 0.1759, 0.7504],
        [0.3048, 0.9453, 0.0054, 0.2815]])

In [8]:
# slicing
x = torch.rand(5,3)
first_column = x[:,0]
x, first_column

(tensor([[0.4345, 0.8765, 0.7068],
         [0.6267, 0.9644, 0.4721],
         [0.7835, 0.2906, 0.2253],
         [0.1909, 0.7015, 0.7442],
         [0.8479, 0.8723, 0.4348]]),
 tensor([0.4345, 0.6267, 0.7835, 0.1909, 0.8479]))